export const PREFERENCE_NAME = 'growing_analytics_sp'
export const PREFERENCE_USER_ID = "growing_user_id"
export const PREFERENCE_USER_KEY = "growing_user_key"
export const PREFERENCE_DEVICE_ID = "growing_device_id"
export const PREFERENCE_EVENT_SEQUENCE_ID = "growing_event_sequence_id"

export const Event_DURATION = "event_duration"

export const SDK_VERSION = "1.0.0"

export type AttributesType = { [key: string]: string | number | boolean | string[] | number[] };